repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-mod-tidy
    - id: go-build

- repo: https://github.com/golangci/golangci-lint
  rev: v1.57.2
  hooks:
    -   id: golangci-lint

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
    - id: prettier
      files: .*.sol$
      additional_dependencies:
        - prettier@2.7.1
        - "prettier-plugin-solidity@1.1.3"
